import { Abi, AbiFunction, AbiInput, AbiOutput } from "../types";

export type EthersCodegenOptions = {
  interfaceName: string;
  contractName: string;
};

const TS_RESERVED = new Set([
  "function", "class", "default", "delete", "new", "let", "const", "var",
  "for", "while", "if", "else", "return", "this", "super", "typeof",
  "instanceof", "interface", "enum", "import", "export", "from", "as",
  "void", "true", "false", "null", "undefined", "yield", "await",
]);

function safeIdent(name: string | undefined, fallbackIdx: number): string {
  if (!name || name.length === 0) return `arg${fallbackIdx}`;
  let cleaned = name.replace(/[^A-Za-z0-9_]/g, "_");
  if (/^[0-9]/.test(cleaned)) cleaned = `_${cleaned}`;
  if (TS_RESERVED.has(cleaned)) cleaned = `${cleaned}_`;
  return cleaned;
}

function pascalCase(s: string): string {
  return s
    .replace(/[^A-Za-z0-9]+(.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^[a-z]/, (c) => c.toUpperCase());
}

function tsTypeForAbi(input: AbiInput | AbiOutput): string {
  const arrayMatch = input.type.match(/^(.+?)((?:\[\d*\])+)$/);
  if (arrayMatch) {
    const baseInput = { ...input, type: arrayMatch[1] };
    const suffix = arrayMatch[2].replace(/\d+/g, "");
    return `${tsTypeForAbi(baseInput)}${suffix}`;
  }

  const t = input.type;
  if (t === "address") return "string";
  if (t === "bool") return "boolean";
  if (t === "string") return "string";
  if (/^bytes\d*$/.test(t)) return "string";
  if (/^u?int\d*$/.test(t)) return "bigint";

  if (t === "tuple") {
    const fields = (input.components ?? [])
      .map((c, i) => `${safeIdent(c.name, i)}: ${tsTypeForAbi(c)}`)
      .join("; ");
    return `{ ${fields} }`;
  }

  return "unknown";
}

function returnType(outputs: AbiOutput[] | undefined): string {
  if (!outputs || outputs.length === 0) return "void";
  if (outputs.length === 1) return tsTypeForAbi(outputs[0]);
  return `[${outputs.map(tsTypeForAbi).join(", ")}]`;
}

function isReadOnly(fn: AbiFunction): boolean {
  return fn.stateMutability === "view" || fn.stateMutability === "pure";
}

function renderMethod(fn: AbiFunction): string | null {
  if (!fn.name) return null;

  const params = (fn.inputs ?? []).map(
    (input, idx) => `${safeIdent(input.name, idx)}: ${tsTypeForAbi(input)}`,
  );

  if (fn.stateMutability === "payable") {
    params.push("overrides?: { value?: bigint }");
  }

  const ret = isReadOnly(fn)
    ? `Promise<${returnType(fn.outputs)}>`
    : "Promise<ContractTransactionResponse>";

  const note = isReadOnly(fn) ? "  // read" : "  // write";
  return `${note}\n  ${fn.name}(${params.join(", ")}): ${ret};`;
}

export function generateEthersInterface(
  abi: Abi,
  opts: EthersCodegenOptions,
): string {
  const methods: string[] = [];
  for (const entry of abi) {
    if (entry.type !== "function") continue;
    const m = renderMethod(entry);
    if (m) methods.push(m);
  }

  const attachName = `attach${pascalCase(opts.contractName)}`;
  const abiJson = JSON.stringify(abi, null, 2);

  return `// Auto-generated by Stylus Analytics Suite. Do not edit by hand.
// Source contract: ${opts.contractName}
//
// Drop into a backend or frontend that depends on ethers v6 to call this
// Stylus contract from off-chain. Read methods take a Provider or Signer;
// write methods require a Signer and return a ContractTransactionResponse.

import {
  Contract,
  type ContractTransactionResponse,
  type InterfaceAbi,
  type Provider,
  type Signer,
} from "ethers";

export const ABI: InterfaceAbi = ${abiJson};

export interface ${opts.interfaceName} {
${methods.join("\n")}
}

export function ${attachName}(
  address: string,
  runner: Provider | Signer,
): ${opts.interfaceName} {
  return new Contract(address, ABI, runner) as unknown as ${opts.interfaceName};
}
`;
}
